<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\30-day\static\models\home2.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
	import { AutoColliders } from '@threlte/rapier';

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube002: THREE.Mesh
      Cube003: THREE.Mesh
      Cube004: THREE.Mesh
      Cube024: THREE.Mesh
      Cube024_1: THREE.Mesh
      Plane003: THREE.Mesh
      Plane004: THREE.Mesh
      Plane005: THREE.Mesh
      Plane016: THREE.Mesh
      Plane016_1: THREE.Mesh
      Plane007: THREE.Mesh
      Plane019: THREE.Mesh
      Plane019_1: THREE.Mesh
      Plane020: THREE.Mesh
      Plane020_1: THREE.Mesh
      Plant_1: THREE.Mesh
      Plant_2: THREE.Mesh
      Plant_3: THREE.Mesh
      Plant_4: THREE.Mesh
    }
    materials: {
      ['House.001']: THREE.MeshStandardMaterial
      ['Roof.001']: THREE.MeshStandardMaterial
      ['Material.012']: THREE.MeshStandardMaterial
      ['Material.011']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      ['Land.001']: THREE.MeshStandardMaterial
      ['Log.03']: THREE.MeshStandardMaterial
      ['Log.04']: THREE.MeshStandardMaterial
      ['Material.006']: THREE.MeshStandardMaterial
      Land: THREE.MeshStandardMaterial
      Light: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/home2.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={2.25}>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Cube002.geometry}
          material={gltf.materials['House.001']}
          position={[0, 0.42, -0.15]}
          scale={0.64}
        />
      </AutoColliders>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Cube003.geometry}
          material={gltf.materials['Roof.001']}
          position={[0, 0.4, -0.15]}
          scale={0.64}
        />
      </AutoColliders>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Cube004.geometry}
          material={gltf.materials['Material.012']}
          position={[0.21, 0.05, 0.37]}
          scale={0.64}
        />
      </AutoColliders>
      <T.Group position={[-0.65, 0.12, -0.16]} scale={0.64}>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Cube024.geometry} material={gltf.materials['Material.011']} />
        </AutoColliders>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Cube024_1.geometry} material={gltf.materials['Material.001']} />
        </AutoColliders>
      </T.Group>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plane003.geometry}
          material={gltf.materials['Land.001']}
          position={[-0.02, 0, 0]}
          scale={0.64}
        />
      </AutoColliders>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plane004.geometry}
          material={gltf.materials['Log.03']}
          position={[0.2, 0.23, 0.23]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.64}
        />
      </AutoColliders>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plane005.geometry}
          material={gltf.materials['Land.001']}
          position={[-0.02, -0.05, 0]}
          scale={0.64}
        />
      </AutoColliders>
      <T.Group position={[0.2, 0.23, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={0.64}>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Plane016.geometry} material={gltf.materials['Log.04']} />
        </AutoColliders>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Plane016_1.geometry} material={gltf.materials['Material.006']} />
        </AutoColliders>
      </T.Group>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plane007.geometry}
          material={gltf.materials.Land}
          position={[-0.02, -0.02, 0]}
          scale={0.64}
        />
      </AutoColliders>
      <T.Group position={[-0.26, 0.29, 0.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.64}>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Plane019.geometry} material={gltf.materials['Log.03']} />
        </AutoColliders>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Plane019_1.geometry} material={gltf.materials.Light} />
        </AutoColliders>
      </T.Group>
      <T.Group position={[0.54, 0.29, -0.15]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.64}>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Plane020.geometry} material={gltf.materials['Log.03']} />
        </AutoColliders>
        <AutoColliders shape={"trimesh"}>
          <T.Mesh geometry={gltf.nodes.Plane020_1.geometry} material={gltf.materials.Light} />
        </AutoColliders>
      </T.Group>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plant_1.geometry}
          material={gltf.materials.Land}
          position={[-0.09, 0.04, 0.36]}
          scale={0.64}
        />
      </AutoColliders>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plant_2.geometry}
          material={gltf.materials.Land}
          position={[0.68, 0.04, 0.26]}
          rotation={[0, 0.62, 0]}
          scale={0.64}
        />
      </AutoColliders>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plant_3.geometry}
          material={gltf.materials.Land}
          position={[-0.63, 0.04, 0.26]}
          rotation={[-Math.PI, 1.27, -Math.PI]}
          scale={0.64}
        />
      </AutoColliders>
      <AutoColliders shape={"trimesh"}>
        <T.Mesh
          geometry={gltf.nodes.Plant_4.geometry}
          material={gltf.materials.Land}
          position={[0.7, 0.04, -0.45]}
          rotation={[-Math.PI, 1.1, -Math.PI]}
          scale={0.64}
        />
      </AutoColliders>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
